states = [
    {"name": "Andaman & Nicobar Islands", "bird": "Andaman Wood Pigeon"},
    {"name": "Andhra Pradesh", "bird": "Indian Roller"},
    {"name": "Arunachal Pradesh", "bird": "Great Hornbill"},
    {"name": "Assam", "bird": "White-winged Duck"},
    {"name": "Bihar", "bird": "Indian Roller"},
    {"name": "Chandigarh", "bird": "Indian Grey Hornbill"},
    {"name": "Chhattisgarh", "bird": "Common hill Myna"},
    {"name": "Delhi", "bird": "House Sparrow"},
    {"name": "Goa", "bird": "Black-crested Bulbul"},
    {"name": "Gujarat", "bird": "Great Flamingo"},
    {"name": "Haryana", "bird": "Black Francolin"},
    {"name": "Himachal Pradesh", "bird": "Western Tragopan"},
    {"name": "Jammu and Kashmir", "bird": "Black-necked Crane"},
    {"name": "Jharkhand", "bird": "Asian Koel"},
    {"name": "Karnataka", "bird": "Indian roller"},
    {"name": "Kerela", "bird": "Great Hornbill"},
    {"name": "Lakshadweep", "bird": "Sooty tern"},
    {"name": "Madhya Pradesh", "bird": "Asian Paradise Flycatcher"},
    {"name": "Maharashtra", "bird": "yellow-footed green pigeon"},
    {"name": "Manipur", "bird": "Mrs. Hume’s Pheasant"},
    {"name": "Meghalaya", "bird": "Common Hill Myna"},
    {"name": "Mizoram", "bird": "Mrs. Hume’s Pheasant"},
    {"name": "Nagaland", "bird": "Blyth’s Tragopan"},
    {"name": "Orissa", "bird": "Indian Peafowl"},
    {"name": "Pondicherry", "bird": "Asian Koel"},
    {"name": "Punjab", "bird": "Northern Goshawk"},
    {"name": "Rajasthan", "bird": "Great Indian Bustard"},
    {"name": "Sikkim", "bird": "Blood Pheasant"},
    {"name": "Tamil Nadu", "bird": "Emerald Dove"},
    {"name": "Telangana", "bird": "Indian Roller"},
    {"name": "Tripura", "bird": "Yellow-footed Green Pigeon"},
    {"name": "Uttar Pradesh", "bird": "Sarus Crane"},
    {"name": "Uttrakhand", "bird": "Himalayan Monal"},
    {"name": "West Bengal", "bird": "White–throated Kingfisher"}
];
